nodeLinker: hoisted

overrides:
  "@lezer/common": 1.5.2

allowBuilds:
  esbuild: true
  fs-xattr: false
  macos-alias: false
  msw: false
  puppeteer: false

patchedDependencies:
  '@coderline/alphatab@1.8.4': patches/@coderline__alphatab@1.8.4.patch
